version: "3"
services:
  
  mongo:
    container_name: mongo_poc
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
        - ./../mongo:/home

  postgres:
    container_name: postgres_poc
    image: postgres:13.2
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./../postgres:/home

  python:
    container_name: python_poc
    build: 
        context: .
        dockerfile: ./DockerFile#python
    image: python
    stdin_open: true
    tty: true
    volumes:
      - ./../python:/home
    depends_on:
        - mongo
        - postgres
